### ISSUE TITLE
Issue with openregex-scala

### ISSUE THREAD

**Issue by FAMILIAR-project** [diverse-project/diversifying-descartes#1]
vmacher:diversifying-descartes macher1$ ./sbt-pit.sh openregex-scala
Use of ~/.sbtconfig is deprecated, please migrate global settings to /usr/local/etc/sbtopts
14:22:32 PIT >> INFO : Verbose logging is disabled. If you encounter a problem, please enable it before reporting an issue.
14:22:32 PIT >> INFO : MINION : objc[13354]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/bin/java (0x10e0e84c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10e1614
14:22:32 PIT >> INFO : MINION : e0). One of the two will be used. Which one is undefined.

14:22:32 PIT >> INFO : Sending 0 test classes to minion
14:22:32 PIT >> INFO : Sent tests to minion
14:22:32 PIT >> INFO : MINION : 14:22:32 PIT >> INFO : Checking environment

14:22:32 PIT >> INFO : MINION : 14:22:32 PIT >> SEVERE : JUnit was not found on the classpath. PIT requires JUnit 4.6 or above.
See http://pitest.org for more details.

14:22:32 PIT >> SEVERE : Error generating coverage. Please check that your classpath contains JUnit 4.6 or above.
Exception in thread "main" org.pitest.util.PitError: Coverage generation minion exited abnormally. Please check the classpath.

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.31-b07
Uptime : 501
Input ->
BootClassPathSupported : true

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.31-b07
Uptime : 502
Input ->
BootClassPathSupported : true

	at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:105)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:51)
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:115)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:120)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:50)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:87)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
Caused by: org.pitest.util.PitError: Coverage generation minion exited abnormally. Please check the classpath.

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.31-b07
Uptime : 501
Input ->
BootClassPathSupported : true

	at org.pitest.coverage.execute.DefaultCoverageGenerator.gatherCoverageData(DefaultCoverageGenerator.java:142)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:89)
	... 6 more
vmacher:diversifying-descartes macher1$

**Comment by FAMILIAR-project** [comment]
refinement:


```
Use of ~/.sbtconfig is deprecated, please migrate global settings to /usr/local/etc/sbtopts
14:32:33 PIT >> INFO : ---------------------------------------------------------------------------
14:32:33 PIT >> INFO : Enabled (+) and disabled (-) features.
14:32:33 PIT >> INFO : -----------------------------------------
14:32:33 PIT >> INFO : +FFBLOCK        Filters mutations in code duplicated by finally block inlining
14:32:33 PIT >> INFO : +FSTATI         Filters mutations in static initializers and code called only from them
14:32:33 PIT >> INFO : +FSEQUIVEQUALS  Filters equivalent mutations that affect only performance in short cutting equals methods
14:32:33 PIT >> INFO : +STOP_METHODS   Filters out mutations in methods that are generally of no interest
14:32:33 PIT >> INFO :   [except]        Allows to reinsert some stop methods into the analysis. Possible values are: getter, constant, return_this, deprecated, clinit, enum, empty, delegate, synthetic, return_param, hash_code, empty_array, null_return, setter, to_string
14:32:33 PIT >> INFO : +FFEACH         Filters mutations in compiler generated code that implements for each loops
14:32:33 PIT >> INFO : +FINFINC        Filters mutations to increments that may cause infinite loops
14:32:33 PIT >> INFO : +FFLOOP         Filters any mutations to increments in for loops as they may cause timeouts
14:32:33 PIT >> INFO : +FRETEQUIV      Filters return vals mutants with bytecode equivalent to the unmutated class
14:32:33 PIT >> INFO : +FINULL         Filters mutations in compiler generated code that checks for null by calling getClass
14:32:33 PIT >> INFO : +FTRYWR         Filters mutations in code generated for try with resources statements
14:32:33 PIT >> INFO : +FKOTLIN        Filters out junk mutations in bytecode created by compiler for kotlin language features
14:32:33 PIT >> INFO : +FSTATINIT      Filters mutations in static initializers and code called only from them
14:32:33 PIT >> INFO : +FLOGCALL       Filters mutations in code that makes calls to logging frameworks
14:32:33 PIT >> INFO : +FINFIT         Filters mutations that may cause infinite loops by removing calls to iterator.next
14:32:33 PIT >> INFO : +FANN           Filters mutations in classes and methods with matching annotations of class or runtime retention
14:32:33 PIT >> INFO :   [annotation]    Annotation to avoid (full package name not required)
14:32:33 PIT >> INFO : -CLASSLIMIT     Limits the maximum number of mutations per class
14:32:33 PIT >> INFO :   [limit]         Integer value for maximum mutations to create per class
14:32:33 PIT >> INFO : -EXPORT         Exports mutants bytecode and other details to disk
14:32:33 PIT >> INFO : ---------------------------------------------------------------------------
14:32:33 PIT >> FINE : Running report with ReportOptions [targetClasses=[edu.knowitall.openregex.*], excludedMethods=[], excludedClasses=[], excludedTestClasses=[], codePaths=[/Users/macher1/Documents/SANDBOX/diversifying-descartes/openregex-scala/target/scala-2.12/classes], reportDir=/Users/macher1/Documents/SANDBOX/diversifying-descartes/openregex-scala, historyInputLocation=null, historyOutputLocation=null, sourceDirs=[/Users/macher1/Documents/SANDBOX/diversifying-descartes/openregex-scala/src/main/scala, /Users/macher1/Documents/SANDBOX/diversifying-descartes/openregex-scala/src/test/scala], classPathElements=[/Users/macher1/Documents/SANDBOX/diversifying-descartes/openregex-scala, /Users/macher1/Documents/SANDBOX/diversifying-descartes/bin/pitest-command-line-1.4.8.jar, /Users/macher1/Documents/SANDBOX/diversifying-descartes/bin/pitest-1.4.8.jar, /Users/macher1/Documents/SANDBOX/diversifying-descartes/bin/pitest-entry-1.4.8.jar, /Users/macher1/Documents/SANDBOX/diversifying-descartes/bin/j2html-1.3.0.jar, /Users/macher1/Documents/SANDBOX/diversifying-descartes/bin/descartes-1.2.6-SNAPSHOT.jar, /Users/macher1/Documents/SANDBOX/diversifying-descartes/openregex-scala/target/scala-2.12/classes, edu.knowitall.openregex.*], mutators=[], features=[], dependencyAnalysisMaxDistance=-1, jvmArgs=[-Djava.awt.headless=true], numberOfThreads=1, timeoutFactor=1.25, timeoutConstant=4000, targetTests=[], loggingClasses=[], maxMutationsPerClass=0, verbose=true, failWhenNoMutations=false, outputs=[JSON, ISSUES, METHODS], groupConfig=TestGroupConfig [excludedGroups=[], includedGroups=[]], fullMutationMatrix=false, mutationUnitSize=0, shouldCreateTimestampedReports=true, detectInlinedCode=false, exportLineCoverage=false, mutationThreshold=0, coverageThreshold=0, mutationEngine=descartes, javaExecutable=null, includeLaunchClasspath=true, properties={}, maxSurvivors=-1, excludedRunners=[], includedTestMethods=[], testPlugin=junit, useClasspathJar=false, skipFailingTests=false]
14:32:33 PIT >> FINE : System class path is :/Users/macher1/Documents/SANDBOX/diversifying-descartes/bin/pitest-command-line-1.4.8.jar:/Users/macher1/Documents/SANDBOX/diversifying-descartes/bin/pitest-1.4.8.jar:/Users/macher1/Documents/SANDBOX/diversifying-descartes/bin/pitest-entry-1.4.8.jar:/Users/macher1/Documents/SANDBOX/diversifying-descartes/bin/j2html-1.3.0.jar:/Users/macher1/Documents/SANDBOX/diversifying-descartes/bin/descartes-1.2.6-SNAPSHOT.jar
14:32:33 PIT >> FINE : Maximum available memory is 3641 mb
14:32:34 PIT >> FINE : MINION : Installing PIT agent

14:32:34 PIT >> INFO : MINION : objc[14799]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/bin/java (0x1056ec4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_31.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1057654
14:32:34 PIT >> INFO : MINION : e0). One of the two will be used. Which one is undefined.

14:32:34 PIT >> INFO : Sending 0 test classes to minion
14:32:34 PIT >> INFO : Sent tests to minion
14:32:34 PIT >> INFO : MINION : 14:32:34 PIT >> FINE : Expecting 0 tests classes from parent

14:32:34 PIT >> INFO : MINION : 14:32:34 PIT >> FINE : Tests classes received

14:32:34 PIT >> INFO : MINION : 14:32:34 PIT >> INFO : Checking environment

14:32:34 PIT >> INFO : MINION : 14:32:34 PIT >> SEVERE : JUnit was not found on the classpath. PIT requires JUnit 4.6 or above.
See http://pitest.org for more details.

14:32:34 PIT >> SEVERE : Error generating coverage. Please check that your classpath contains JUnit 4.6 or above.
Exception in thread "main" org.pitest.util.PitError: Coverage generation minion exited abnormally. Please check the classpath.

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.31-b07
Uptime : 542
Input -> 
BootClassPathSupported : true


Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.31-b07
Uptime : 543
Input -> 
BootClassPathSupported : true

	at org.pitest.util.Unchecked.translateCheckedException(Unchecked.java:20)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:105)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:51)
	at org.pitest.mutationtest.tooling.MutationCoverage.runReport(MutationCoverage.java:115)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:120)
	at org.pitest.mutationtest.tooling.EntryPoint.execute(EntryPoint.java:50)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.runReport(MutationCoverageReport.java:87)
	at org.pitest.mutationtest.commandline.MutationCoverageReport.main(MutationCoverageReport.java:45)
Caused by: org.pitest.util.PitError: Coverage generation minion exited abnormally. Please check the classpath.

Please copy and paste the information and the complete stacktrace below when reporting an issue
VM : Java HotSpot(TM) 64-Bit Server VM
Vendor : Oracle Corporation
Version : 25.31-b07
Uptime : 542
Input -> 
BootClassPathSupported : true

	at org.pitest.coverage.execute.DefaultCoverageGenerator.gatherCoverageData(DefaultCoverageGenerator.java:142)
	at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:89)
	... 6 more

```
